name: darkradiant
version: '2.5.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Level editing tool for The Dark Mod and Doom 3
description: |
  DarkRadiant is a level editing tool for the open source stealth game The Dark
  Mod, which is available separately from http://www.thedarkmod.com. It is also
  possible to edit levels for Doom 3 and possibly other games using a similar
  engine, such as Quake 4, although these are not officially supported.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  darkradiant:
    command: desktop-launch $SNAP/bin/darkradiant
    plugs: [desktop, gsettings, home, opengl, pulseaudio, x11]

parts:
  darkradiant:
    after: [desktop-gtk2]
    plugin: autotools
    configflags:
      - --enable-darkmod-plugins
      - --enable-relocation
    install-via: prefix
    source: .
