name: CMake

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  Linux-Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Package Dependencies
      run: |
        sudo apt-get update 
        sudo apt-get install -yq gettext pkg-config zlib1g-dev libjpeg-dev libxml2-dev libsigc++-2.0-dev
        sudo apt-get install -yq libgtest-dev libeigen3-dev libwxgtk3.0-gtk3-dev libpng-dev 
        sudo apt-get install -yq libftgl-dev libglew-dev libalut-dev libvorbis-dev python3-dev

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      env: 
        CMAKE_BUILD_PARALLEL_LEVEL: 3
        CTEST_OUTPUT_ON_FAILURE: ON
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Run Unit Tests
      env: 
        DR_VERBOSE_TEST_LOG: ON
      shell: bash
      run: ctest -C $BUILD_TYPE --output-log dr-test-run.log --verbose
      
    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: unit-test-results
        path: dr-test-run.log
